global:
  resolve_timeout: 30s

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  # Add a default receiver for unmatched alerts
  receiver: 'snmp_notifier'
  routes:
    - matchers:
        - alertname=~"ExampleAlertHELIX|HighCPUUsage"
        - severity="critical"
      receiver: 'webhook'

    - match:
        alertname: "ExampleAlertSNMP"
        severity: "critical"
      receiver: 'snmp_notifier'

    - match:
        alertname: "HighDiskSpace"
        severity: "warning"
      receiver: 'snmp_notifier'

receivers:
  - name: 'snmp_notifier'
    webhook_configs:
      - url: "http://localhost:9464/alerts"  # Ensure this URL is correct and accessible
        send_resolved: true

  - name: 'webhook'
    webhook_configs:
      - url: "http://localhost:5000/submit"
        send_resolved: true
